
server:
  port: 8081
  contextPath: /

spring:
  application:
    name: spring-cloud-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:7070/authserver/oauth/token
      userAuthorizationUri: http://localhost:7070/authserver/oauth/authorize
      clientId: second
      clientSecret: passwordforauthserver
    resource:
      userInfoUri: http://localhost:9000/user

person:
  url: http://localhost:9000/person


zuul:
  routes:
    resource:
      path: /api/**
      url: http://localhost:9000
    user: 
      path: /user/**
      url: http://localhost:9000/user

proxy:
  auth:
    routes:
      api: oauth2