server:
  port: 8010
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kingswwong/spring-cloud-learning
          search-paths: config
          username: kingswwong
          password: 19961223cxy
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
