spring:
  application:
    name: spring-cloud-user-client
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19961223
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/










